Metadrop/behat-contexts

- Behat/Context/DebugContext.php
Add functionality to name the files with the date and not be overwritten and call the appropriate metados and pass the appropriate parameters
> Fb context debug

- Behat/Context/UIContext.php
There is a debug trace in the step
> Remove print_r in iSelectFromChosenJsSelectBox

- Behat/Context/UIContext.php
Added new step to fill a ckeditor widget.
The idea is taken from https://gist.github.com/johnennewdeeson/240e2b60c23ea3217887
But the step is named with Ckeditor as it is Ckeditor depedent
> New step: iFillInCkeditorOnFieldWith

- Behat/Context/DrupalExtendedContext.php
Added new steps to flush drupal cache.
It is useful when the anonymous cache is active.
> New steps: cachePageIsFlushed cacheViewsDataIsFlushed

- Behat/Context/DrupalExtendedContext.php
I've added a new step to easily go to last entity created.
Useful after entity creation through  "given" sentence.
please review!
> New step: go to the last entity created

- Behat/Context/DrupalExtendedContext.php
> Added I run elysia cron job step

- Behat/Context/DrupalExtendedContext.php
> Added Step to refresh node access for the last created node

- Behat/Context/DrupalExtendedContext.php
Added new step to create entity files in drupal. It takes care of created files and delete them in the after scenario.
please review!
> Added new step: file create

- Behat/Context/DrupalExtendedContext.php
Add a new step to wait for any batch process.
The step looks for a unique identifier used by the batch processes.
> Add Step: Wait for batch process

- Behat/Context/DebugContext.php
I would be great if the report files generated are available by url, for example for CI integration.
A new configuration variable is added: error_reporting_url': "http://worldarchery.me/sites/default/files/"
Example: '
```
...
'error_reporting_path': "/var/vhost/mysite-local/codebase/docroot/sites/default/files/behat/errors"
'error_reporting_url': "http://customsite.local/sites/default/files/behat/errors"
...
```
If there is any error the output will prompt:
```
│  Error generated reports:
│   - info (exception): http://customsite.local/sites/default/files/behat/errors/Error-20170610--17-27-11-.58089700_anonymous.world_records_line_97.txt
│   - html (output): http://customsite.local/sites/default/files/behat/errors/Error-20170610--17-27-11-.58089700_anonymous.world_records_line_97.html
│ …
```
> Refactor saveReport() and print reports url to better CI integration

- Behat/Context/DrupalExtendedContext.php
- Behat/Context/DrupalOrganicGroupsExtendedContext.php
Hi, I had this changes for the namespace Exception -> \Exception, because when I execute the tests I can see this error 'Fatal error: Class 'Metadrop\Behat\Context\Exception' not found (Behat\Testwork\Call\Exception\FatalThrowableError)'. 
Please review, Thank.
> Fix namespace - Exception -> \Exception

- Behat/Context/UIContext.php
New param added to UIContext named customParams.
Added scroll functions to selector and field.
> Added scroll to steps: Element and field

- Behat/Context/UIContext.php
getElementByXpath
theElementShouldHaveAttributeWithValue
theElementShouldNotHaveAttributeWithValue
> Add - Test - Element should have attribute

- Behat/Context/UIContext.php
The condition_error_string var was in the wrong order.
> Update UIContext overwrite condition error string

- Behat/Context/UIContext.php
Hi, I revised the file, and Fixed the coding standards.
> Coding Standard UIContext

- Behat/Context/DrupalExtendedContext.php
Created step check that user with mail exists or not exists.
> Created step check that user with mail exists or not exists.

- Behat/Context/UIContext.php
Added one second wait for scroll script execution.
> UiContext - Scroll to selector function - Added one second wait

- Behat/Context/DrupalExtendedContext.php
Created step check param with value in url.
> Created step check param with value in url.

- Behat/Context/DrupalExtendedContext.php
Create paragraphs and reference it to the last node of type given.
> Create paragraphs and reference it to the last node of type given.

- composer.json
This allows add namespacing available for behat contexts in behat.yml.
> Add autoload settings for composer.json

- src/Behat/Context/DebugContext.php
Debug context and added method to set file name if not exists in generate capture step.
> Debug context and method to set file name if not exists

- src/Behat/Context/EntityContext.php
- src/Behat/Cores/CoreInterface.php
- src/Behat/Cores/Drupal7.php
- src/Behat/Cores/Drupal8.php
- src/Behat/Cores/Traits/CronTrait.php
- src/Behat/Cores/Traits/FileTrait.php
- src/Behat/Cores/Traits/UsersTrait.php
> Coding standards.

- README.md
- src/Behat/Context/EntityContext.php
- src/Behat/Cores/CoreInterface.php
- src/Behat/Cores/Drupal7.php
- src/Behat/Cores/Drupal8.php
Purge entities created during the baht execution.
Yo can defined a list of entities to remove.
> Purge entities

- src/Behat/Context/DebugContext.php
Prevent duplicate class error.
> Delete use RawDrupalContext from the debug Context

- src/Behat/Cores/Drupal7.php
Added methods to the core Drupal 7 to check entity fields.
Its brings you the ability of check fields of an specific entity by its fields.
Use example of use:
Configure behat.yml
```
default:
...
suites:
default:
...
contexts:
- Metadrop\Behat\Context\EntityContext
.....
```
Use example feature:
```
@behat @api
Scenario: Check entity values
Then the 'user' with field 'mail' and value 'behat@metadrop.net' should have the following values:
| mail                             | uid                                                                                  | roles                       |
| behat@metadrop.net  | entity-replacement:user:mail:behat@metadrop.net:uid | authenticated user |
```
> Added methods to drupal 7 to check Entity fields.

- src/Behat/Context/FileContext.php
- src/Behat/Cores/CoreInterface.php
- src/Behat/Cores/Drupal7.php
- src/Behat/Cores/Drupal8.php
Created new method to get public or private file path indendent of manually setup.
> File context: get file from file context method

- src/Behat/Context/WaitingContext.php
> Add a the right sentences for waiting steps, and increment timeout to 30 secs

- src/Behat/Context/EntityContext.php
- src/Behat/Cores/CoreInterface.php
- src/Behat/Cores/Drupal7.php
- src/Behat/Cores/Drupal8.php
- src/Behat/Cores/Traits/EntityTrait.php
These steps provides a way to access to an entity with an specific label during tests.
> Steps to go to an entity with a specific label

- src/Behat/Context/UIContext.php
This step allows fill a drupal multiple field.
The step has an strong dependency with the default administration markup html markup, it assumes it won't be modified. I currently don't know how to remove the dependency, any help is welcome.
> Step to fill a multiple field.

- src/Behat/Context/LogsContext.php
> User wid variable because $log variable is not set.

- src/Behat/Cores/CoreInterface.php
- src/Behat/Cores/Drupal7.php
- src/Behat/Cores/Drupal8.php
> Allow to clear entity static cache.

- src/Behat/Context/UsersContext.php
This completes https://github.com/Metadrop/behat-contexts/issues/86
> Refactor userRoleCheck: clear static cache, split into smaller functions.

- src/Behat/Context/CronContext.php
- src/Behat/Cores/CoreInterface.php
- src/Behat/Cores/Drupal7.php
- src/Behat/Cores/Drupal8.php
I was developing a new step to run ultimate cron jobs, but I saw that Behat CronContext already have a method to run an specific cron from module but it does not have a step for it, so I added to this pull request.
I added both, because we use ultimate cron on multiple sites.
> Added step to run module cron.

- README.md
> Change repo on README.md to metadrop

- src/Behat/Context/EntityContext.php
- src/Behat/Context/FileContext.php
- src/Behat/Cores/CoreInterface.php
- src/Behat/Cores/Drupal7.php
- src/Behat/Cores/Drupal8.php
- Step to go to a file.
- Allow reference images in 'Given entity' step
> Improve files testing

- src/Behat/Context/FormContext.php
Remove unexpected comma on FormContext
> Remove unexpected comma

- src/Behat/Context/EntityContext.php
- src/Behat/Cores/CoreInterface.php
- src/Behat/Cores/Drupal7.php
- src/Behat/Cores/Drupal8.php
> Allow declare language prefix on step go to

- src/Behat/Context/EntityContext.php
Added a new step to go an entity subpath in a concrete language.
> Allow to go to a subpath in a language

- composer.json
> Require metadrop/drupal-behat to D9 and D10 compatibility

- src/Behat/Context/DebugContext.php
> Issue #154: Filename on saveIntoFile method should be mandatory

- src/Behat/Context/DebugContext.php
- src/Behat/Context/DrupalGroupsExtendedContext.php
- src/Behat/Context/DrupalOrganicGroupsExtendedContext.php
- src/Behat/Context/EntityContext.php
- src/Behat/Context/UIContext.php
> Issue #151: Remove deprecated SnippetAcceptingContext

- composer.json
- src/Behat/Context/LogsContext.php
- src/Behat/Context/RawDrupalContext.php
- src/Behat/Cores/CoreInterface.php
- src/Behat/Cores/Drupal7.php
- src/Behat/Cores/Drupal8.php
> Issue #153: Group watchdog logs when finish the suite

- src/Behat/Context/LogsContext.php
Add time to log to distinguish between execution reports.
> Add time to log

- README.md
- src/Behat/Context/CookieComplianceContext.php
This PR adds a context and its documentation to allow testing the sites are cookie compliant and cover this subject in terms of GDPR compliance.
> Allow testing that sites are cookie compliant

- src/Behat/Cores/Drupal7.php
- src/Behat/Cores/Drupal8.php
- src/Behat/Cores/Traits/FileTrait.php
> Issue #147: Deprecated function file_save_data

- README.md
- src/Behat/Context/UIContext.php
> Issue #139: Create method to check an item position

- src/Behat/Context/CookieComplianceContext.php
Allow to check specific cookies and their value.
> Check especific cookie value

- src/Behat/Context/CookieComplianceContext.php
Error with method cookieExistsWithValue because cookie_value is undefined.
> Fix error cookie value

- src/Behat/Context/VideoRecordingContext.php
Detect arguments object type on VideoRecordingContext
> Added logic to support Pystring as arguments
