Behat/Context/UIContext.php

PhantomJS is not compatible with file field multiple and crashes.
This workarround removes the property, this way the test can upload at least one file to the widget.

New step: fileFieldIsNotMultiple

---

Behat/Context/DrupalExtendedContext.php

Comparation should be case insensitive as drupal does not let you create two role names like: "Member" and "member".
This path helps with false possitive: "the user does not have the role Member", and the user does have the role "member" (which should be the same)

userShouldHaveTheRole: case insensitive

---

Behat/Context/DrupalExtendedContext.php

function userShouldNotHaveTheRole
Gherkin, call function without "s". Role instead of roles use plural with (s)

Fix - Context - DruaplExtendedContext - Call to function

---

Behat/Context/DrupalExtendedContext.php

Hi.
I made a new step. It's the same step than 'I wait for AJAX to finish' from drupal extension but you can specify the time to wait. In addition, if time to wait is excedded and AJAX didn't finish, throw the Exception.
By this way we can set a correct time for each specific request, and mark test as failed when AJAX call didn't completed, instead of show a error in the next steps.
Can you review and merge this? Thanks!

New step: wait for ajax specifying time to wait.

---

Behat/Context/DebugContext.php

The windowResize method called by captureFullPageWithWidthOfToWithName expects a number not a string: so casting it.
And capture full page with a width of 1200
java.lang.String cannot be cast to java.lang.Number (WebDriver\Exception\UnknownError)

BUGFIX: captureFullPageWithWidthOfToWithName expects number

---

Behat/Context/DrupalOrganicGroupsExtendedContext.php

Hello.
I was using this library to make tests in my Drupal projects.
I needed make steps in order to subscribe user in a organic group. 
So I created a branch with a context which provides methods (no steps) to subscribe user to groups, easy to implement in steps. 
There are 2 methods: one subscribes user in a group, and the other subscribes user and give specific group role.
Can you review this, and merge if you like? Thanks!

Fb organic groups context

---

Behat/Context/UIContext.php

Hi I've added to steps to click on an element with CSS and XPath. Also a shortcut for labels.
When you use Chrome (Chromedriver) if the radiobuttons/checkboxes are themed in a special way (they are hidden and some tricky css are replacing them) is common to see the message:
```
When I select the radio button “Militaire”
unknown error: Element <input data-drupal-selector=“edit-status-militaire” type=“radio” id=“edit-status-militaire” name=“status” value=“militaire” class=“form-radio”> is not clickable at point (336, 271). Other element would receive the click: <div class=“js-form-item form-item js-form-type-radio form-type-radio js-form-item-status form-item-status”>...</div>
```
So we need a step to click directly on the label which is been shown.
In this commit, there are a global …

Added steps: click element with xpath/css + label

---

Behat/Context/UIContext.php

We use the scroll when we need to move to a specific part of the page, it does not need to be realistic and it needs to be as fast as possible to avoid using "and I wait X seconds" after each step.
Attaching patch applying ZERO latency to the scroll step.
please review

Quickest scroll: scrollToSelector ZERO latency

---

Behat/Context/UIContext.php

Hi. In this pull request I add namespace for ExpectationException in order to prevent this fatal error:
`PHP Fatal error:  Class 'Metadrop\Behat\Context\ExpectationException' not found`
Can you merge this? Thanks!

Add namespace required to throw ExpectationException

---

Behat/Context/DebugContext.php

Version behat3.3 trigger Error Unsupported operand.

Correctly name protected variable customParams to customParameters.

---

Behat/Context/BrowserSizeContext.php
Behat/Context/DrupalExtendedContext.php

Hi.
In new versions of behat (behat3.3-dev)  $this->user can't be used directly, it should be used $this->getUserManager() methods instead.
This PR fix the usage of $this->user in all parts of code is being used:
- Steps to check user role
- Given own content step
This force to use behat3.3 version, we may make a fallback for previous versions?

Compatibility with behat3.3: usage of $this->user

---

src/Behat/Context/FormContext.php

The step element is required but only checked the class, in drupal 8 the required class is not added so it must check the attribute required.

Added check by attribute required

---

src/Behat/Context/EntityContext.php
src/Behat/Cores/CoreInterface.php
src/Behat/Cores/Drupal7.php
src/Behat/Cores/Drupal8.php

I added a custom step to check the values of a entity, an also to have a token to replace in the check.
Here is an example:
* And entity of type 'user' with field 'mail' and value 'behat@metadrop.net' should have the following values:
*  | mail                             | uid                                                                                  |
*  | behat@metadrop.net  | entity-replacement:user:mail:behat@metadrop.net:uid |
This example checks the entity "user", and makes an entity query to get the entity, using the condition field mail has the value behat@metadrop.net.
Also in the Table checks the value mail, and the uid but in the uid field makes a replacement.
The replacement woks with the word entity-replacement : entity type : key field : key value

Added custom step to check entity values.

---

src/Behat/Context/DrupalOrganicGroupsExtendedContext.php

prevent "already used class" error, as in other contexts

Comment use Drupal\DrupalExtension\Context\RawDrupalContext

---

services.yml
src/Behat/Context/Annotation/Reader.php
src/Behat/Context/EntityContext.php
src/Behat/Context/RawDrupalContext.php
src/Behat/Hook/Call/AfterEntityCreate.php
src/Behat/Hook/Call/BeforeEntityCreate.php
src/Behat/Hook/Scope/AfterEntityCreateScope.php
src/Behat/Hook/Scope/BeforeEntityCreateScope.php
src/Behat/Hook/Scope/EntityScope.php

This pull request allow write steps to create any kind of drupal entity:
`@Given :entity_type entity:`
It is useful in the case you want create custom entities during tests so you don't need to create a special step for that. It can be repetitive, and a generic step reduce costs.

Provide a generic step to create entities

---

src/Behat/Context/EntityContext.php
src/Behat/Cores/CoreInterface.php
src/Behat/Cores/Drupal7.php
src/Behat/Cores/Drupal8.php

The `Given :entity entity` step does not remove the generated entities after the scenario ends, like the given node, or given user contexts does.
This PR provides methods to delete every generated entity after the scenario.

Delete the generated entities by the EntityContext class.

---

src/Behat/Context/EntityContext.php

When working on a project, I was trying to create a media entity referencing a file with the following code:
```gherkin
Background:
Given file with name "dummy.pdf"
And users:
| name         |
| behat_test   |
And "media" entity:
| bundle       | field_private_file | revision_user | name        | status |
| private_file | dummy.pdf         | behat_test     | behat_media | 1      |
```
But the code didn't create a reference from the media entity to the file entity, making the tests fail.
When debugging I found that the reason was that the `entityCreate` function only considers the fields of type "entity_reference" as references.
Fields of type "file" should be also included, as they hold references to file entities. The PR solves this.

Consider file field type as reference field on entity creation.

---

src/Behat/Cores/Drupal8.php

Since both d8 and d9 have the entity_type.manager service but d9 does
not have entity.manager service, entity_type.manager should be used for
both versions.

Change entityManager in favour of entityTypeManager.

---

src/Behat/Context/StateContextTrait.php
src/Behat/Cores/CoreInterface.php
src/Behat/Cores/Drupal7.php
src/Behat/Cores/Drupal8.php

This comes from this https://github.com/Metadrop/behat-contexts/pull/62.
That PR creates a StateContext with a step like: 
`Given I set the state key "state_key_name" to "state_value"`
While is nice to be able to change Drupal State in Behat test, tests should be legible for humans. Using state keys and values is probably not legible. Also, most of the steps that need to change the state are probably very specific for one site.  So, we can create a PHP Trait with all the hard stuff to alter Drupal State, so any site can add it to its FeatureContext and create simple steps that use the API provided by the trait modifies the state.
For example, let's say we want to alter the key "my_obscure_key.obscure_propery" and set the "obscureValue" value.
WIth a StateContext it will be:
`Given I set …

Add a trait to handle Drupal state to use on FeatureContext classes

---

src/Behat/Context/UIContext.php

Added new step to UiContext to check if a input is disabled by the label.
Example:
`Then I check the input with "Email" label is disabled`

Added step to check input is disabled.

---

src/Behat/Context/AntiSpamContext.php
src/Behat/Context/FormContext.php
src/Behat/Cores/Drupal7.php
src/Behat/Cores/Drupal8.php

This PR adds a beforeScenario and afterScenario (using the tag honeypot-disable) that will deactivate the time limit during the test in order to allow form submissions without honeypot interference.

Allows to disable honeypot time limit in order to perform automated form submissions

---

src/Behat/Context/EntityContext.php
src/Behat/Cores/CoreInterface.php
src/Behat/Cores/Drupal7.php
src/Behat/Cores/Drupal8.php

This issue addresses two problems arised when deleting entities either on an @AfterScenario or by using @purgeEntities tag.
- Entities are deleted on the generation order (first in, first out). If there is any hierarchical relationship (for example, on the Group and Subgroup modules) it will cause errors as there are guards that prevent the parent removal if there are any child still present.
This PR uses array_reverse() in order to assure that the order is last in, first out.
- On purgeEntities, this PR adds an ->accessCheck(FALSE) because it defaults to true and might easily result on the entities not being purged.

Ensure entities are cleaned on correct order and access check is bypassed

---

src/Behat/Context/EntityContext.php
src/Behat/Cores/CoreInterface.php
src/Behat/Cores/Drupal7.php
src/Behat/Cores/Drupal8.php

On some scenarios, the `entityDelete()` methods won't receive an updated version of the entity to delete (the entity could have been changed because, as part of the test, some values were implicit or explicitly changed).
This can lead to errors if there are some dependencies. In the case of Subgroup, the Group entity was cached and the values that reflect the hierarchy were missing when the deletion was triggered. This led to exceptions.
There is a new parameter ($reset_caches) that can be passed to entity deletion methods. This parameter will ensure that an up-to-date entity is deleted.

Allow to define wether the entity cache should be reset prior to deletion

---

src/Behat/Context/EntityContext.php

When method entityCreate creates an entity with a referenced entity field without value, the process breaks.

Add extra validation target_id in entityCreate

---

README.md
src/Behat/Context/WaitingContext.php

This context provides waiting time after defined steps, and extra waiting steps.
Waiting steps - Sometimes steps are running faster than our site, if this is the case you can delay them a few seconds. Don't abuse of this functionality, if Behat is running slow maybe there is a performance global site issue that needs to be solved first!

Configure on behat.yml waiting steps before next steps.

---

src/Behat/Context/DrupalGroupsExtendedContext.php

@Given the user :user_name is the owner of the group type :group_type with name :group_name step was setting correctly owner but with no effect due group is not saved.

User name is the owner of the group unsaved group

---

src/Behat/Context/I18nContext.php
src/Behat/Context/MediaContext.php
src/Behat/Context/UsersRandomContext.php

In the cases that it is needed to extend MinkContext (s.e.: trying to wrap a specific MinkContext step), there is an error saying that `Drupal\DrupalExtension\Context\MinkContext`does not exist. It happens because the specific Drupal extension's MinkContext class is required in some contexts:
- https://github.com/Metadrop/behat-contexts/blob/master/src/Behat/Context/I18nContext.php
- https://github.com/Metadrop/behat-contexts/blob/master/src/Behat/Context/MediaContext.php
- https://github.com/Metadrop/behat-contexts/blob/master/src/Behat/Context/UsersRandomContext.php
But looking deeply in the code, the context doesn't need to be an instance of  `Drupal\DrupalExtension\Context\MinkContext`, just an instance of `\Behat\MinkExtension\Context\MinkContext`.
Change the behat.yml class of …

MINK - Require a class that extends MinkContext instead of Drupal\DrupalExtension\Context\MinkContext

---

src/Behat/Context/UsersRandomContext.php

Currently, the UserRandomContext has methods to fill forms with random values, but it does not allow filling fields in a specific region. It is necessary sometimes where there are more than one form in the same page with same field names . For example, a page with both user login and user register forms.

RANDOM CONTEXT - Allow fill random values into a region

---

src/Behat/Context/LogsContext.php

Remove dirname to get the right path.
Jenkins is failing because the wrong path /job/..../job/tests/job/PR-183/10/consoleFull
```
Error when executing always post condition:
java.io.IOException: .../reports/behat/dblog does not exist.
```
```
Created dblog report on /var/www/html/docroot/../reports/behat/report_dblog-2023-03-21-11-14-41.csv
```
And this is because the dirname function removes the last part of the path. Dirname was mandatory when the path included the report file name, but now it should be removed to get the right dirname.

Remove dirname to get the right path

---

src/Behat/Context/CookieComplianceContext.php

After accepting the cookie banner, we should check if the banner is null or not visible.
In the case of OneTrust, the banner is set to display none and visibility: hidden instead of deleting the banner, so the current step does not work in those cases.
As a solution, we can check if the banner is present but also check the visibility of the element.
There are a lot of solutions on JS to check if an element is visible and maybe this one is not the best, but for this case, seems to work.
Other solutions are listed here https://stackoverflow.com/questions/19669786/check-if-element-is-visible-in-dom
If we decide on a more accurate solution, please add it to the PR.

COOKIES - After accept check if the banner is null or not visible

---

src/Behat/Context/UrlContext.php

When the URL query is not set, then parse_url returns a null, parse_str expects a string, and if a null is given, then an error is thrown.
```
And current url should not have the "s" param with "ar" value
8192: parse_str(): Passing null to parameter #1 ($string) of type string is deprecated in vendor/metadrop/behat-contexts/src/Behat/Context/UrlContext.php line 17
```
Because the Context also checks when a param is not set when any query params are empty are also valid.

Parse str expects string, null given

---

src/Behat/Context/MediaContext.php

Currently, the media upload step contains the string "Select " which makes the step incompatible if you are not using English on the website.
I have added and checked a correction to be able to upload media independently of the language of the site where Behat tests are being launched.

Upload media independent of language

---

composer.json

The original repository has been updated with the changes introduced by the Metadrop fork, so the dependency is removed.
https://github.com/nuvoleweb/drupal-behat

Remove dependency with "Metadrop/drupal-behat" fork

---

src/Behat/Context/EntityContext.php
src/Behat/Cores/CoreInterface.php
src/Behat/Cores/Drupal7.php
src/Behat/Cores/Drupal8.php

- All methods that visit entities use the same method
- Now the relative path is generated using Drupal\Core\Url class so code is not dependent of language detection method

Standardize and refactor the way entity urls are being visited in contexts

---

src/Behat/Context/UIContext.php

On behat text, when I try to interact with an iframe, I get this warning:
The test works, but this warnings tag the test as failed. The Context property iframe must be declared.

Added Context property to avoid dynamic creation of iframe property

---

composer.json

Hi, I have some requirements running Behat for Drupal 11.
Running test, I need this dependency: "webmozart/path-util": "^2.0", but when I downloaded using -W, it's not getting installed.
I guess that can be setted in the composer dependencies.
Thanks in advance.
NOTE: "metadrop/behat-contexts": "^1.3", === 1.20.3 version.

Required "webmozart/path-util": "^2.0" as dependency
